{
 "title": "NGINX exporter",
 "description": "Official dashboard for NGINX Prometheus exporter for https://github.com/nginxinc/nginx-prometheus-exporter",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(nginx_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processed connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_ingress_controller_nginx_process_connections_total{state=\"accepted\"}[2m])",
     "legendFormat": "Accepted"
    },
    {
     "expr": "irate(nginx_ingress_controller_nginx_process_connections_total{state=\"handled\"}[2m])",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginx_ingress_controller_nginx_process_connections{state=\"active\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "nginx_ingress_controller_nginx_process_connections{state=\"reading\"}",
     "legendFormat": "Reading"
    },
    {
     "expr": "nginx_ingress_controller_nginx_process_connections{state=\"waiting\"}",
     "legendFormat": "Waiting"
    },
    {
     "expr": "nginx_ingress_controller_nginx_process_connections{state=\"writing\"}",
     "legendFormat": "Writing"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "irate(nginx_ingress_controller_nginx_process_resident_memory_bytes[2m])",
     "legendFormat": "In use"
    },
    {
     "expr": "nginx_ingress_controller_nginx_process_virtual_memory_bytes",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_ingress_controller_nginx_process_requests_total{}[5m])",
     "legendFormat": "{{instance}} total requests"
    }
   ]
  }
 ]
}