apiVersion: v1
kind: Endpoints
metadata:
  name: database
subsets:
- addresses:
  # IP address associated with the Docker bridge network interface `docker0`
  - ip: 172.17.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  clusterIP: None