apiVersion: apps/v1
kind: Deployment
metadata:
  name: v1-apiexpress-deployment
  labels:
    app: v1-apiexpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: v1-apiexpress
  template:
    metadata:
      labels:
        app: v1-apiexpress
    spec:
      restartPolicy: Always
      containers:
        - name: v1-apiexpress
          image: apiexpress:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                  secretKeyRef:
                    name: database-secret
                    key: host
            - name: DB_USER
              valueFrom:
                  secretKeyRef:
                    name: database-secret
                    key: user
            - name: DB_PASS
              valueFrom:
                  secretKeyRef:
                    name: database-secret
                    key: pass
            - name: DB_NAME
              valueFrom:
                  secretKeyRef:
                    name: database-secret
                    key: name