services:
  postgres:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_database:/var/lib/postgresql/data
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
    env_file:
      - ./database.env
    network_mode: host

volumes:
  pg_database:
